version: '3.8'

services:
  app-prod:
    image: ha1fdan/bolt-ai-production:0.0.3
    ports:
      - "5173:5173"
    env_file: ".env.local"
    environment:
      - NODE_ENV=production
      - COMPOSE_PROFILES=production
      - PORT=5173
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HuggingFace_API_KEY=${HuggingFace_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - TOGETHER_API_BASE_URL=${TOGETHER_API_BASE_URL}
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-debug}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
      - RUNNING_IN_DOCKER=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bolt.entrypoints=websecure"
      - "traefik.http.routers.bolt.rule=Host(`bolt.2damoon.xyz`)"
      - "traefik.http.routers.bolt.tls.certresolver=letsencrypt"
      - "traefik.http.services.bolt.loadbalancer.server.port=5173"
    command: pnpm run dockerstart
    profiles:
      - production
    networks:
      - caddy_default

  app-dev:
    image: ghcr.io/stackblitz-labs/bolt.diy:3be18e3
    hostname: bolt
    environment:
      - NODE_ENV=development
      - VITE_HMR_PROTOCOL=ws
      - VITE_HMR_HOST=localhost
      - VITE_HMR_PORT=5173
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - PORT=5173
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HuggingFace_API_KEY=${HuggingFace_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_LIKE_API_KEY=sk-FiIu6b1Hyq7TDX-C9phogQ
      - OPENAI_LIKE_API_BASE_URL=https://litellm.2damoon.xyz
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPEN_ROUTER_API_KEY=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
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - TOGETHER_API_BASE_URL=${TOGETHER_API_BASE_URL}
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-debug}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
      - RUNNING_IN_DOCKER=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bolt.entrypoints=websecure"
      - "traefik.http.routers.bolt.rule=Host(`bolt.2damoon.xyz`)"
      - "traefik.http.routers.bolt.tls.certresolver=letsencrypt"
      - "traefik.http.services.bolt.loadbalancer.server.port=5173"
    volumes:
      - type: bind
        source: .
        target: /app
        consistency: cached
      - /app/node_modules
    ports:
      - "5174:5173"
    command: pnpm run dev --host 0.0.0.0
    profiles: ["development", "default"]
    networks:
      - caddy_default

networks:
  caddy_default:
    external: true
